import apiSlice from "../apiSlice";

type ShopProductParams = {
  page?: number;
  limit?: number;
  category?: string;
  company?: string;
  model?: string;
  year?: number;
  search?: string;
};

export const productApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Endpoint to list products with filters
    listProductForShop: builder.query({
      query: (params) => ({
        url: "/v1/product/list/shop",
        params,
      }),
    }),
    // Endpoint to get product detail by slug
    productDetailForShop: builder.query<any, string>({
      query: (slug) => ({
        url: `/v1/product/list/shop/${slug}`,
      }),
    }),
  }),
  overrideExisting: false,
});

// Hooks generated by RTK Query
export const { 
  useListProductForShopQuery, 
  useProductDetailForShopQuery 
} = productApi;
